<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Append Child Page' => '',
  'Append Sibling Page' => '',
  'Chapter contains no sections' => '',
  'Click Start upload' => '',
  'Create' => '',
  'DataChunks' => '',
  'Drag & drop the file you wish to upload or use the select button below' => '',
  'Exercises' => '',
  'Index' => '',
  'Name' => '',
  'No processed media file available' => '',
  'Presentations' => '',
  'Section contains no sectionContents' => '',
  'Section content has no linked content' => '',
  'SectionContents' => '',
  'Sitemap' => '',
  'SpreadsheetFiles' => '',
  'Template' => '',
  'Update' => '',
  'When upload has been completed, click Save to return to the previous form' => '',
  'Widgets' => '',
  'About' => '@@Über uns@@',
  'Contact Us' => '@@Kontakt@@',
  'Error' => '@@Fehler@@',
  'Fields with' => '@@Felder mit@@',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => '@@Sollten Sie geschäftliche oder sonstige Frage haben, verwenden Sie bitte das folgende Formular. Vielen Dank.@@',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => '@@Bitte geben Sie die nebenstehenden Buchstaben ein.<br/>Groß- und Kleinschreibung ist nicht zu beachten.@@',
  'Submit' => '@@Senden@@',
  'This is a "static" page. You may change the content of this page by updating the file' => '@@Dies ist eine "statische" Seite. Um den Inhalt anzupassen, verändern Sie die Datei@@',
  'are required' => '@@sind erforderlich@@',
  'Application' => 'Anwendung',
  'Body' => 'Nachricht',
  'Browse' => 'Verwalten',
  'Choose Language' => 'Sprache wechseln',
  'Email' => 'E-Mail',
  'List' => 'Liste',
  'Login' => 'Anmelden',
  'Logout' => 'Abmelden',
  'Manage' => 'Verwalten',
  'Media' => 'Medien',
  'Overview' => 'Übersicht',
  'Pages' => 'Seiten',
  'Profile' => 'Profil',
  'Rights' => 'Rechte',
  'Settings' => 'Einstellungen',
  'Subject' => 'Betreff',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden Ihnen schnellstmöglich antworten.',
  'Translation' => 'Übersetzung',
  'Upload' => 'Hochladen',
  'User' => 'Benutzer',
  'Users' => 'Benutzer',
  'Verification Code' => 'Verifizierungscode',
);
