<?php
class m131017_120644_qa_attributes extends CDbMigration
{
    public function up()
    {
        $this->createTable('chapter_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('chapter', 'chapter_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('chapter_qa_state_id_fk', 'chapter', 'chapter_qa_state_id', 'chapter_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('chapter_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('chapter_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'thumbnail_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'about_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'video_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'teachers_guide_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'exercises_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'snapshots_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'credits_approved', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'thumbnail_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'about_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'video_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'teachers_guide_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'exercises_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'snapshots_proofed', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'credits_proofed', 'BOOLEAN NULL');
        $this->createTable('data_chunk_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('data_chunk', 'data_chunk_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('data_chunk_qa_state_id_fk', 'data_chunk', 'data_chunk_qa_state_id', 'data_chunk_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('data_chunk_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('data_chunk_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('data_chunk_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'file_approved', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('data_chunk_qa_state', 'file_proofed', 'BOOLEAN NULL');
        $this->createTable('data_source_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('data_source', 'data_source_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('data_source_qa_state_id_fk', 'data_source', 'data_source_qa_state_id', 'data_source_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('data_source_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('data_source_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'link_approved', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'link_proofed', 'BOOLEAN NULL');
        $this->createTable('exam_question_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('exam_question', 'exam_question_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('exam_question_qa_state_id_fk', 'exam_question', 'exam_question_qa_state_id', 'exam_question_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('exam_question_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('exam_question_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'question_approved', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'source_approved', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'question_proofed', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'source_proofed', 'BOOLEAN NULL');
        $this->createTable('exercise_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('exercise', 'exercise_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('exercise_qa_state_id_fk', 'exercise', 'exercise_qa_state_id', 'exercise_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('exercise_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('exercise_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'question_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'description_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'thumbnail_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'materials_approved', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'question_proofed', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'description_proofed', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'thumbnail_proofed', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'materials_proofed', 'BOOLEAN NULL');
        $this->createTable('po_file_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('po_file', 'po_file_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('po_file_qa_state_id_fk', 'po_file', 'po_file_qa_state_id', 'po_file_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('po_file_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('po_file_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('po_file_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'file_approved', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('po_file_qa_state', 'file_proofed', 'BOOLEAN NULL');
        $this->createTable('slideshow_file_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('slideshow_file', 'slideshow_file_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('slideshow_file_qa_state_id_fk', 'slideshow_file', 'slideshow_file_qa_state_id', 'slideshow_file_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('slideshow_file_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('slideshow_file_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'file_approved', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'file_proofed', 'BOOLEAN NULL');
        $this->createTable('snapshot_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('snapshot', 'snapshot_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('snapshot_qa_state_id_fk', 'snapshot', 'snapshot_qa_state_id', 'snapshot_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('snapshot_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('snapshot_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'link_approved', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'link_proofed', 'BOOLEAN NULL');
        $this->createTable('text_doc_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('text_doc', 'text_doc_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('text_doc_qa_state_id_fk', 'text_doc', 'text_doc_qa_state_id', 'text_doc_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('text_doc_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('text_doc_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'file_approved', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'file_proofed', 'BOOLEAN NULL');
        $this->createTable('tool_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('tool', 'tool_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('tool_qa_state_id_fk', 'tool', 'tool_qa_state_id', 'tool_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('tool_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('tool_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->createTable('vector_graphic_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('vector_graphic', 'vector_graphic_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('vector_graphic_qa_state_id_fk', 'vector_graphic', 'vector_graphic_qa_state_id', 'vector_graphic_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('vector_graphic_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('vector_graphic_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'file_approved', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'file_proofed', 'BOOLEAN NULL');
        $this->createTable('video_file_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('video_file', 'video_file_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('video_file_qa_state_id_fk', 'video_file', 'video_file_qa_state_id', 'video_file_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('video_file_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('video_file_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'translations_draft_validation_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'translations_preview_validation_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'translations_public_validation_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'translations_approval_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'translations_proofing_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'slug_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'about_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'thumbnail_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'subtitles_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'slug_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'about_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'thumbnail_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'subtitles_proofed', 'BOOLEAN NULL');
    }

    public function down()
    {
      $this->dropForeignKey('chapter_qa_state_id_fk', 'chapter');
      $this->dropColumn('chapter', 'chapter_qa_state_id');
      $this->dropTable('chapter_qa_state');
      $this->dropColumn('chapter_qa_state', 'status');
      $this->dropColumn('chapter_qa_state', 'draft_validation_progress');
      $this->dropColumn('chapter_qa_state', 'preview_validation_progress');
      $this->dropColumn('chapter_qa_state', 'public_validation_progress');
      $this->dropColumn('chapter_qa_state', 'approval_progress');
      $this->dropColumn('chapter_qa_state', 'proofing_progress');
      $this->dropColumn('chapter_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('chapter_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('chapter_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('chapter_qa_state', 'translations_approval_progress');
      $this->dropColumn('chapter_qa_state', 'translations_proofing_progress');
      $this->dropColumn('chapter_qa_state', 'previewing_welcome');
      $this->dropColumn('chapter_qa_state', 'candidate_for_public_status');
      $this->dropColumn('chapter_qa_state', 'title_approved');
      $this->dropColumn('chapter_qa_state', 'slug_approved');
      $this->dropColumn('chapter_qa_state', 'thumbnail_approved');
      $this->dropColumn('chapter_qa_state', 'about_approved');
      $this->dropColumn('chapter_qa_state', 'video_approved');
      $this->dropColumn('chapter_qa_state', 'teachers_guide_approved');
      $this->dropColumn('chapter_qa_state', 'exercises_approved');
      $this->dropColumn('chapter_qa_state', 'snapshots_approved');
      $this->dropColumn('chapter_qa_state', 'credits_approved');
      $this->dropColumn('chapter_qa_state', 'title_proofed');
      $this->dropColumn('chapter_qa_state', 'slug_proofed');
      $this->dropColumn('chapter_qa_state', 'thumbnail_proofed');
      $this->dropColumn('chapter_qa_state', 'about_proofed');
      $this->dropColumn('chapter_qa_state', 'video_proofed');
      $this->dropColumn('chapter_qa_state', 'teachers_guide_proofed');
      $this->dropColumn('chapter_qa_state', 'exercises_proofed');
      $this->dropColumn('chapter_qa_state', 'snapshots_proofed');
      $this->dropColumn('chapter_qa_state', 'credits_proofed');
      $this->dropForeignKey('data_chunk_qa_state_id_fk', 'data_chunk');
      $this->dropColumn('data_chunk', 'data_chunk_qa_state_id');
      $this->dropTable('data_chunk_qa_state');
      $this->dropColumn('data_chunk_qa_state', 'status');
      $this->dropColumn('data_chunk_qa_state', 'draft_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'preview_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'public_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'approval_progress');
      $this->dropColumn('data_chunk_qa_state', 'proofing_progress');
      $this->dropColumn('data_chunk_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('data_chunk_qa_state', 'translations_approval_progress');
      $this->dropColumn('data_chunk_qa_state', 'translations_proofing_progress');
      $this->dropColumn('data_chunk_qa_state', 'previewing_welcome');
      $this->dropColumn('data_chunk_qa_state', 'candidate_for_public_status');
      $this->dropColumn('data_chunk_qa_state', 'slug_approved');
      $this->dropColumn('data_chunk_qa_state', 'title_approved');
      $this->dropColumn('data_chunk_qa_state', 'file_approved');
      $this->dropColumn('data_chunk_qa_state', 'slug_proofed');
      $this->dropColumn('data_chunk_qa_state', 'title_proofed');
      $this->dropColumn('data_chunk_qa_state', 'file_proofed');
      $this->dropForeignKey('data_source_qa_state_id_fk', 'data_source');
      $this->dropColumn('data_source', 'data_source_qa_state_id');
      $this->dropTable('data_source_qa_state');
      $this->dropColumn('data_source_qa_state', 'status');
      $this->dropColumn('data_source_qa_state', 'draft_validation_progress');
      $this->dropColumn('data_source_qa_state', 'preview_validation_progress');
      $this->dropColumn('data_source_qa_state', 'public_validation_progress');
      $this->dropColumn('data_source_qa_state', 'approval_progress');
      $this->dropColumn('data_source_qa_state', 'proofing_progress');
      $this->dropColumn('data_source_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('data_source_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('data_source_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('data_source_qa_state', 'translations_approval_progress');
      $this->dropColumn('data_source_qa_state', 'translations_proofing_progress');
      $this->dropColumn('data_source_qa_state', 'previewing_welcome');
      $this->dropColumn('data_source_qa_state', 'candidate_for_public_status');
      $this->dropColumn('data_source_qa_state', 'slug_approved');
      $this->dropColumn('data_source_qa_state', 'title_approved');
      $this->dropColumn('data_source_qa_state', 'link_approved');
      $this->dropColumn('data_source_qa_state', 'slug_proofed');
      $this->dropColumn('data_source_qa_state', 'title_proofed');
      $this->dropColumn('data_source_qa_state', 'link_proofed');
      $this->dropForeignKey('exam_question_qa_state_id_fk', 'exam_question');
      $this->dropColumn('exam_question', 'exam_question_qa_state_id');
      $this->dropTable('exam_question_qa_state');
      $this->dropColumn('exam_question_qa_state', 'status');
      $this->dropColumn('exam_question_qa_state', 'draft_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'preview_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'public_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'approval_progress');
      $this->dropColumn('exam_question_qa_state', 'proofing_progress');
      $this->dropColumn('exam_question_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'translations_approval_progress');
      $this->dropColumn('exam_question_qa_state', 'translations_proofing_progress');
      $this->dropColumn('exam_question_qa_state', 'previewing_welcome');
      $this->dropColumn('exam_question_qa_state', 'candidate_for_public_status');
      $this->dropColumn('exam_question_qa_state', 'slug_approved');
      $this->dropColumn('exam_question_qa_state', 'question_approved');
      $this->dropColumn('exam_question_qa_state', 'source_approved');
      $this->dropColumn('exam_question_qa_state', 'slug_proofed');
      $this->dropColumn('exam_question_qa_state', 'question_proofed');
      $this->dropColumn('exam_question_qa_state', 'source_proofed');
      $this->dropForeignKey('exercise_qa_state_id_fk', 'exercise');
      $this->dropColumn('exercise', 'exercise_qa_state_id');
      $this->dropTable('exercise_qa_state');
      $this->dropColumn('exercise_qa_state', 'status');
      $this->dropColumn('exercise_qa_state', 'draft_validation_progress');
      $this->dropColumn('exercise_qa_state', 'preview_validation_progress');
      $this->dropColumn('exercise_qa_state', 'public_validation_progress');
      $this->dropColumn('exercise_qa_state', 'approval_progress');
      $this->dropColumn('exercise_qa_state', 'proofing_progress');
      $this->dropColumn('exercise_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('exercise_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('exercise_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('exercise_qa_state', 'translations_approval_progress');
      $this->dropColumn('exercise_qa_state', 'translations_proofing_progress');
      $this->dropColumn('exercise_qa_state', 'previewing_welcome');
      $this->dropColumn('exercise_qa_state', 'candidate_for_public_status');
      $this->dropColumn('exercise_qa_state', 'title_approved');
      $this->dropColumn('exercise_qa_state', 'slug_approved');
      $this->dropColumn('exercise_qa_state', 'question_approved');
      $this->dropColumn('exercise_qa_state', 'description_approved');
      $this->dropColumn('exercise_qa_state', 'thumbnail_approved');
      $this->dropColumn('exercise_qa_state', 'materials_approved');
      $this->dropColumn('exercise_qa_state', 'title_proofed');
      $this->dropColumn('exercise_qa_state', 'slug_proofed');
      $this->dropColumn('exercise_qa_state', 'question_proofed');
      $this->dropColumn('exercise_qa_state', 'description_proofed');
      $this->dropColumn('exercise_qa_state', 'thumbnail_proofed');
      $this->dropColumn('exercise_qa_state', 'materials_proofed');
      $this->dropForeignKey('po_file_qa_state_id_fk', 'po_file');
      $this->dropColumn('po_file', 'po_file_qa_state_id');
      $this->dropTable('po_file_qa_state');
      $this->dropColumn('po_file_qa_state', 'status');
      $this->dropColumn('po_file_qa_state', 'draft_validation_progress');
      $this->dropColumn('po_file_qa_state', 'preview_validation_progress');
      $this->dropColumn('po_file_qa_state', 'public_validation_progress');
      $this->dropColumn('po_file_qa_state', 'approval_progress');
      $this->dropColumn('po_file_qa_state', 'proofing_progress');
      $this->dropColumn('po_file_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('po_file_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('po_file_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('po_file_qa_state', 'translations_approval_progress');
      $this->dropColumn('po_file_qa_state', 'translations_proofing_progress');
      $this->dropColumn('po_file_qa_state', 'previewing_welcome');
      $this->dropColumn('po_file_qa_state', 'candidate_for_public_status');
      $this->dropColumn('po_file_qa_state', 'title_approved');
      $this->dropColumn('po_file_qa_state', 'file_approved');
      $this->dropColumn('po_file_qa_state', 'title_proofed');
      $this->dropColumn('po_file_qa_state', 'file_proofed');
      $this->dropForeignKey('slideshow_file_qa_state_id_fk', 'slideshow_file');
      $this->dropColumn('slideshow_file', 'slideshow_file_qa_state_id');
      $this->dropTable('slideshow_file_qa_state');
      $this->dropColumn('slideshow_file_qa_state', 'status');
      $this->dropColumn('slideshow_file_qa_state', 'draft_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'preview_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'public_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'approval_progress');
      $this->dropColumn('slideshow_file_qa_state', 'proofing_progress');
      $this->dropColumn('slideshow_file_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'translations_approval_progress');
      $this->dropColumn('slideshow_file_qa_state', 'translations_proofing_progress');
      $this->dropColumn('slideshow_file_qa_state', 'previewing_welcome');
      $this->dropColumn('slideshow_file_qa_state', 'candidate_for_public_status');
      $this->dropColumn('slideshow_file_qa_state', 'slug_approved');
      $this->dropColumn('slideshow_file_qa_state', 'title_approved');
      $this->dropColumn('slideshow_file_qa_state', 'file_approved');
      $this->dropColumn('slideshow_file_qa_state', 'slug_proofed');
      $this->dropColumn('slideshow_file_qa_state', 'title_proofed');
      $this->dropColumn('slideshow_file_qa_state', 'file_proofed');
      $this->dropForeignKey('snapshot_qa_state_id_fk', 'snapshot');
      $this->dropColumn('snapshot', 'snapshot_qa_state_id');
      $this->dropTable('snapshot_qa_state');
      $this->dropColumn('snapshot_qa_state', 'status');
      $this->dropColumn('snapshot_qa_state', 'draft_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'preview_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'public_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'approval_progress');
      $this->dropColumn('snapshot_qa_state', 'proofing_progress');
      $this->dropColumn('snapshot_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'translations_approval_progress');
      $this->dropColumn('snapshot_qa_state', 'translations_proofing_progress');
      $this->dropColumn('snapshot_qa_state', 'previewing_welcome');
      $this->dropColumn('snapshot_qa_state', 'candidate_for_public_status');
      $this->dropColumn('snapshot_qa_state', 'slug_approved');
      $this->dropColumn('snapshot_qa_state', 'link_approved');
      $this->dropColumn('snapshot_qa_state', 'slug_proofed');
      $this->dropColumn('snapshot_qa_state', 'link_proofed');
      $this->dropForeignKey('text_doc_qa_state_id_fk', 'text_doc');
      $this->dropColumn('text_doc', 'text_doc_qa_state_id');
      $this->dropTable('text_doc_qa_state');
      $this->dropColumn('text_doc_qa_state', 'status');
      $this->dropColumn('text_doc_qa_state', 'draft_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'preview_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'public_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'approval_progress');
      $this->dropColumn('text_doc_qa_state', 'proofing_progress');
      $this->dropColumn('text_doc_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'translations_approval_progress');
      $this->dropColumn('text_doc_qa_state', 'translations_proofing_progress');
      $this->dropColumn('text_doc_qa_state', 'previewing_welcome');
      $this->dropColumn('text_doc_qa_state', 'candidate_for_public_status');
      $this->dropColumn('text_doc_qa_state', 'slug_approved');
      $this->dropColumn('text_doc_qa_state', 'title_approved');
      $this->dropColumn('text_doc_qa_state', 'file_approved');
      $this->dropColumn('text_doc_qa_state', 'slug_proofed');
      $this->dropColumn('text_doc_qa_state', 'title_proofed');
      $this->dropColumn('text_doc_qa_state', 'file_proofed');
      $this->dropForeignKey('tool_qa_state_id_fk', 'tool');
      $this->dropColumn('tool', 'tool_qa_state_id');
      $this->dropTable('tool_qa_state');
      $this->dropColumn('tool_qa_state', 'status');
      $this->dropColumn('tool_qa_state', 'draft_validation_progress');
      $this->dropColumn('tool_qa_state', 'preview_validation_progress');
      $this->dropColumn('tool_qa_state', 'public_validation_progress');
      $this->dropColumn('tool_qa_state', 'approval_progress');
      $this->dropColumn('tool_qa_state', 'proofing_progress');
      $this->dropColumn('tool_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('tool_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('tool_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('tool_qa_state', 'translations_approval_progress');
      $this->dropColumn('tool_qa_state', 'translations_proofing_progress');
      $this->dropColumn('tool_qa_state', 'previewing_welcome');
      $this->dropColumn('tool_qa_state', 'candidate_for_public_status');
      $this->dropColumn('tool_qa_state', 'title_approved');
      $this->dropColumn('tool_qa_state', 'slug_approved');
      $this->dropColumn('tool_qa_state', 'title_proofed');
      $this->dropColumn('tool_qa_state', 'slug_proofed');
      $this->dropForeignKey('vector_graphic_qa_state_id_fk', 'vector_graphic');
      $this->dropColumn('vector_graphic', 'vector_graphic_qa_state_id');
      $this->dropTable('vector_graphic_qa_state');
      $this->dropColumn('vector_graphic_qa_state', 'status');
      $this->dropColumn('vector_graphic_qa_state', 'draft_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'preview_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'public_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'approval_progress');
      $this->dropColumn('vector_graphic_qa_state', 'proofing_progress');
      $this->dropColumn('vector_graphic_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'translations_approval_progress');
      $this->dropColumn('vector_graphic_qa_state', 'translations_proofing_progress');
      $this->dropColumn('vector_graphic_qa_state', 'previewing_welcome');
      $this->dropColumn('vector_graphic_qa_state', 'candidate_for_public_status');
      $this->dropColumn('vector_graphic_qa_state', 'slug_approved');
      $this->dropColumn('vector_graphic_qa_state', 'title_approved');
      $this->dropColumn('vector_graphic_qa_state', 'file_approved');
      $this->dropColumn('vector_graphic_qa_state', 'slug_proofed');
      $this->dropColumn('vector_graphic_qa_state', 'title_proofed');
      $this->dropColumn('vector_graphic_qa_state', 'file_proofed');
      $this->dropForeignKey('video_file_qa_state_id_fk', 'video_file');
      $this->dropColumn('video_file', 'video_file_qa_state_id');
      $this->dropTable('video_file_qa_state');
      $this->dropColumn('video_file_qa_state', 'status');
      $this->dropColumn('video_file_qa_state', 'draft_validation_progress');
      $this->dropColumn('video_file_qa_state', 'preview_validation_progress');
      $this->dropColumn('video_file_qa_state', 'public_validation_progress');
      $this->dropColumn('video_file_qa_state', 'approval_progress');
      $this->dropColumn('video_file_qa_state', 'proofing_progress');
      $this->dropColumn('video_file_qa_state', 'translations_draft_validation_progress');
      $this->dropColumn('video_file_qa_state', 'translations_preview_validation_progress');
      $this->dropColumn('video_file_qa_state', 'translations_public_validation_progress');
      $this->dropColumn('video_file_qa_state', 'translations_approval_progress');
      $this->dropColumn('video_file_qa_state', 'translations_proofing_progress');
      $this->dropColumn('video_file_qa_state', 'previewing_welcome');
      $this->dropColumn('video_file_qa_state', 'candidate_for_public_status');
      $this->dropColumn('video_file_qa_state', 'title_approved');
      $this->dropColumn('video_file_qa_state', 'slug_approved');
      $this->dropColumn('video_file_qa_state', 'clip_approved');
      $this->dropColumn('video_file_qa_state', 'about_approved');
      $this->dropColumn('video_file_qa_state', 'thumbnail_approved');
      $this->dropColumn('video_file_qa_state', 'subtitles_approved');
      $this->dropColumn('video_file_qa_state', 'title_proofed');
      $this->dropColumn('video_file_qa_state', 'slug_proofed');
      $this->dropColumn('video_file_qa_state', 'clip_proofed');
      $this->dropColumn('video_file_qa_state', 'about_proofed');
      $this->dropColumn('video_file_qa_state', 'thumbnail_proofed');
      $this->dropColumn('video_file_qa_state', 'subtitles_proofed');
    }
}
