<?php
class m140124_103340_qa_attributes extends CDbMigration
{
    public function up()
    {
        $this->createTable('page_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('page', 'page_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('page_qa_state_id_fk', 'page', 'page_qa_state_id', 'page_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('page_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('page_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_en_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ar_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_bg_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ca_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_cs_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_da_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_de_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_en_gb_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_en_us_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_el_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_es_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_fi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_fil_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_fr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_hi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_hr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_hu_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_id_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_iw_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_it_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ja_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ko_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_lt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_lv_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_nl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_no_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_pl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_pt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_pt_br_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_pt_pt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ro_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_ru_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_sk_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_sl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_sr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_sv_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_th_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_tr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_uk_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_vi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_zh_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_zh_cn_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'translate_into_zh_tw_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('page_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('page_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'title_en_approved', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'slug_en_approved', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'title_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'slug_en_proofed', 'BOOLEAN NULL');
        $this->createTable('section_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('section', 'section_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('section_qa_state_id_fk', 'section', 'section_qa_state_id', 'section_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('section_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('section_qa_state', 'draft_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'preview_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'public_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_en_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ar_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_bg_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ca_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_cs_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_da_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_de_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_en_gb_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_en_us_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_el_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_es_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_fi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_fil_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_fr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_hi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_hr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_hu_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_id_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_iw_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_it_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ja_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ko_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_lt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_lv_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_nl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_no_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_pl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_pt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_pt_br_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_pt_pt_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ro_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_ru_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_sk_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_sl_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_sr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_sv_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_th_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_tr_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_uk_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_vi_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_zh_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_zh_cn_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'translate_into_zh_tw_validation_progress', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('section_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('section_qa_state', 'previewing_welcome', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'candidate_for_public_status', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'title_en_approved', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'slug_en_approved', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'title_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'slug_en_proofed', 'BOOLEAN NULL');
    }

    public function down()
    {
      $this->dropForeignKey('page_qa_state_id_fk', 'page');
      $this->dropColumn('page', 'page_qa_state_id');
      $this->dropTable('page_qa_state');
      $this->dropColumn('page_qa_state', 'status');
      $this->dropColumn('page_qa_state', 'draft_validation_progress');
      $this->dropColumn('page_qa_state', 'preview_validation_progress');
      $this->dropColumn('page_qa_state', 'public_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_en_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ar_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_bg_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ca_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_cs_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_da_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_de_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_en_gb_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_en_us_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_el_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_es_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_fi_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_fil_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_fr_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_hi_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_hr_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_hu_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_id_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_iw_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_it_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ja_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ko_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_lt_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_lv_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_nl_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_no_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_pl_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_pt_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_pt_br_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_pt_pt_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ro_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_ru_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_sk_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_sl_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_sr_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_sv_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_th_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_tr_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_uk_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_vi_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_zh_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_zh_cn_validation_progress');
      $this->dropColumn('page_qa_state', 'translate_into_zh_tw_validation_progress');
      $this->dropColumn('page_qa_state', 'approval_progress');
      $this->dropColumn('page_qa_state', 'proofing_progress');
      $this->dropColumn('page_qa_state', 'previewing_welcome');
      $this->dropColumn('page_qa_state', 'candidate_for_public_status');
      $this->dropColumn('page_qa_state', 'title_en_approved');
      $this->dropColumn('page_qa_state', 'slug_en_approved');
      $this->dropColumn('page_qa_state', 'title_en_proofed');
      $this->dropColumn('page_qa_state', 'slug_en_proofed');
      $this->dropForeignKey('section_qa_state_id_fk', 'section');
      $this->dropColumn('section', 'section_qa_state_id');
      $this->dropTable('section_qa_state');
      $this->dropColumn('section_qa_state', 'status');
      $this->dropColumn('section_qa_state', 'draft_validation_progress');
      $this->dropColumn('section_qa_state', 'preview_validation_progress');
      $this->dropColumn('section_qa_state', 'public_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_en_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ar_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_bg_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ca_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_cs_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_da_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_de_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_en_gb_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_en_us_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_el_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_es_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_fi_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_fil_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_fr_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_hi_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_hr_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_hu_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_id_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_iw_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_it_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ja_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ko_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_lt_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_lv_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_nl_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_no_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_pl_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_pt_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_pt_br_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_pt_pt_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ro_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_ru_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_sk_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_sl_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_sr_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_sv_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_th_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_tr_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_uk_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_vi_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_zh_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_zh_cn_validation_progress');
      $this->dropColumn('section_qa_state', 'translate_into_zh_tw_validation_progress');
      $this->dropColumn('section_qa_state', 'approval_progress');
      $this->dropColumn('section_qa_state', 'proofing_progress');
      $this->dropColumn('section_qa_state', 'previewing_welcome');
      $this->dropColumn('section_qa_state', 'candidate_for_public_status');
      $this->dropColumn('section_qa_state', 'title_en_approved');
      $this->dropColumn('section_qa_state', 'slug_en_approved');
      $this->dropColumn('section_qa_state', 'title_en_proofed');
      $this->dropColumn('section_qa_state', 'slug_en_proofed');
    }
}
