<?php
class m140305_085103_qa_attributes extends CDbMigration
{
    public function up()
    {
        $this->addColumn('chapter_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('chapter_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('chapter_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('data_article_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('data_article_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('data_article_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('data_article_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('data_source_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('download_link_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('download_link_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('download_link_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('download_link_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('exam_question_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('exam_question_alternative_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_alternative_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('exam_question_alternative_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('exam_question_alternative_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('exercise_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('exercise_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('gui_section_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('gui_section_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('gui_section_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('gui_section_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('html_chunk_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('html_chunk_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('html_chunk_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('html_chunk_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('i18n_catalog_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('i18n_catalog_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('i18n_catalog_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('i18n_catalog_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('menu_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('menu_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('menu_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('menu_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('page_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('page_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('page_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('section_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('section_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('section_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('slideshow_file_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('slideshow_file_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('snapshot_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('snapshot_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->createTable('spreadsheet_file_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('spreadsheet_file', 'spreadsheet_file_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('spreadsheet_file_qa_state_id_fk', 'spreadsheet_file', 'spreadsheet_file_qa_state_id', 'spreadsheet_file_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'draft_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_en_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ar_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_bg_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ca_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_cs_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_da_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_de_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_en_gb_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_en_us_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_el_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_es_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_fi_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_fil_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_fr_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_hi_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_hr_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_hu_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_id_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_iw_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_it_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ja_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ko_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_lt_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_lv_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_nl_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_no_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_pl_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_pt_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_pt_br_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_pt_pt_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ro_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_ru_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_sk_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_sl_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_sr_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_sv_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_th_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_tr_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_uk_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_vi_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_zh_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_zh_cn_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'translate_into_zh_tw_validation_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'slug_en_approved', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'title_en_approved', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'original_media_id_approved', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'processed_media_id_en_approved', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'slug_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'title_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'original_media_id_proofed', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'processed_media_id_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('spreadsheet_file_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('text_doc_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('text_doc_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('tool_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('tool_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('vector_graphic_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('vector_graphic_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('video_file_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_category_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_category_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_element_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_category_element_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_category_element_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_element_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_data_source_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_data_source_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_indicator_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_indicator_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_tag_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_tag_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_unit_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_unit_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'allow_publish', 'BOOLEAN NULL');
    }

    public function down()
    {
      $this->dropColumn('chapter_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('chapter_qa_state', 'publishable_validation_progress');
      $this->dropColumn('chapter_qa_state', 'allow_review');
      $this->dropColumn('chapter_qa_state', 'allow_publish');
      $this->dropColumn('data_article_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('data_article_qa_state', 'publishable_validation_progress');
      $this->dropColumn('data_article_qa_state', 'allow_review');
      $this->dropColumn('data_article_qa_state', 'allow_publish');
      $this->dropColumn('data_source_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('data_source_qa_state', 'publishable_validation_progress');
      $this->dropColumn('data_source_qa_state', 'allow_review');
      $this->dropColumn('data_source_qa_state', 'allow_publish');
      $this->dropColumn('download_link_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('download_link_qa_state', 'publishable_validation_progress');
      $this->dropColumn('download_link_qa_state', 'allow_review');
      $this->dropColumn('download_link_qa_state', 'allow_publish');
      $this->dropColumn('exam_question_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'publishable_validation_progress');
      $this->dropColumn('exam_question_qa_state', 'allow_review');
      $this->dropColumn('exam_question_qa_state', 'allow_publish');
      $this->dropColumn('exam_question_alternative_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('exam_question_alternative_qa_state', 'publishable_validation_progress');
      $this->dropColumn('exam_question_alternative_qa_state', 'allow_review');
      $this->dropColumn('exam_question_alternative_qa_state', 'allow_publish');
      $this->dropColumn('exercise_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('exercise_qa_state', 'publishable_validation_progress');
      $this->dropColumn('exercise_qa_state', 'allow_review');
      $this->dropColumn('exercise_qa_state', 'allow_publish');
      $this->dropColumn('gui_section_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('gui_section_qa_state', 'publishable_validation_progress');
      $this->dropColumn('gui_section_qa_state', 'allow_review');
      $this->dropColumn('gui_section_qa_state', 'allow_publish');
      $this->dropColumn('html_chunk_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('html_chunk_qa_state', 'publishable_validation_progress');
      $this->dropColumn('html_chunk_qa_state', 'allow_review');
      $this->dropColumn('html_chunk_qa_state', 'allow_publish');
      $this->dropColumn('i18n_catalog_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('i18n_catalog_qa_state', 'publishable_validation_progress');
      $this->dropColumn('i18n_catalog_qa_state', 'allow_review');
      $this->dropColumn('i18n_catalog_qa_state', 'allow_publish');
      $this->dropColumn('menu_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('menu_qa_state', 'publishable_validation_progress');
      $this->dropColumn('menu_qa_state', 'allow_review');
      $this->dropColumn('menu_qa_state', 'allow_publish');
      $this->dropColumn('page_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('page_qa_state', 'publishable_validation_progress');
      $this->dropColumn('page_qa_state', 'allow_review');
      $this->dropColumn('page_qa_state', 'allow_publish');
      $this->dropColumn('section_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('section_qa_state', 'publishable_validation_progress');
      $this->dropColumn('section_qa_state', 'allow_review');
      $this->dropColumn('section_qa_state', 'allow_publish');
      $this->dropColumn('slideshow_file_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'publishable_validation_progress');
      $this->dropColumn('slideshow_file_qa_state', 'allow_review');
      $this->dropColumn('slideshow_file_qa_state', 'allow_publish');
      $this->dropColumn('snapshot_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'publishable_validation_progress');
      $this->dropColumn('snapshot_qa_state', 'allow_review');
      $this->dropColumn('snapshot_qa_state', 'allow_publish');
      $this->dropForeignKey('spreadsheet_file_qa_state_id_fk', 'spreadsheet_file');
      $this->dropColumn('spreadsheet_file', 'spreadsheet_file_qa_state_id');
      $this->dropTable('spreadsheet_file_qa_state');
      $this->dropColumn('spreadsheet_file_qa_state', 'status');
      $this->dropColumn('spreadsheet_file_qa_state', 'draft_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'publishable_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_en_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ar_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_bg_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ca_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_cs_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_da_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_de_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_en_gb_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_en_us_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_el_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_es_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_fi_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_fil_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_fr_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_hi_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_hr_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_hu_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_id_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_iw_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_it_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ja_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ko_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_lt_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_lv_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_nl_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_no_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_pl_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_pt_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_pt_br_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_pt_pt_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ro_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_ru_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_sk_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_sl_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_sr_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_sv_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_th_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_tr_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_uk_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_vi_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_zh_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_zh_cn_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'translate_into_zh_tw_validation_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'approval_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'proofing_progress');
      $this->dropColumn('spreadsheet_file_qa_state', 'allow_review');
      $this->dropColumn('spreadsheet_file_qa_state', 'allow_publish');
      $this->dropColumn('spreadsheet_file_qa_state', 'slug_en_approved');
      $this->dropColumn('spreadsheet_file_qa_state', 'title_en_approved');
      $this->dropColumn('spreadsheet_file_qa_state', 'original_media_id_approved');
      $this->dropColumn('spreadsheet_file_qa_state', 'processed_media_id_en_approved');
      $this->dropColumn('spreadsheet_file_qa_state', 'title_approved');
      $this->dropColumn('spreadsheet_file_qa_state', 'slug_en_proofed');
      $this->dropColumn('spreadsheet_file_qa_state', 'title_en_proofed');
      $this->dropColumn('spreadsheet_file_qa_state', 'original_media_id_proofed');
      $this->dropColumn('spreadsheet_file_qa_state', 'processed_media_id_en_proofed');
      $this->dropColumn('spreadsheet_file_qa_state', 'title_proofed');
      $this->dropColumn('text_doc_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'publishable_validation_progress');
      $this->dropColumn('text_doc_qa_state', 'allow_review');
      $this->dropColumn('text_doc_qa_state', 'allow_publish');
      $this->dropColumn('tool_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('tool_qa_state', 'publishable_validation_progress');
      $this->dropColumn('tool_qa_state', 'allow_review');
      $this->dropColumn('tool_qa_state', 'allow_publish');
      $this->dropColumn('vector_graphic_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'publishable_validation_progress');
      $this->dropColumn('vector_graphic_qa_state', 'allow_review');
      $this->dropColumn('vector_graphic_qa_state', 'allow_publish');
      $this->dropColumn('video_file_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('video_file_qa_state', 'publishable_validation_progress');
      $this->dropColumn('video_file_qa_state', 'allow_review');
      $this->dropColumn('video_file_qa_state', 'allow_publish');
      $this->dropColumn('waffle_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_qa_state', 'allow_review');
      $this->dropColumn('waffle_qa_state', 'allow_publish');
      $this->dropColumn('waffle_category_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_category_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_category_qa_state', 'allow_review');
      $this->dropColumn('waffle_category_qa_state', 'allow_publish');
      $this->dropColumn('waffle_category_element_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_category_element_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_category_element_qa_state', 'allow_review');
      $this->dropColumn('waffle_category_element_qa_state', 'allow_publish');
      $this->dropColumn('waffle_data_source_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_data_source_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_data_source_qa_state', 'allow_review');
      $this->dropColumn('waffle_data_source_qa_state', 'allow_publish');
      $this->dropColumn('waffle_indicator_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_indicator_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_indicator_qa_state', 'allow_review');
      $this->dropColumn('waffle_indicator_qa_state', 'allow_publish');
      $this->dropColumn('waffle_tag_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_tag_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_tag_qa_state', 'allow_review');
      $this->dropColumn('waffle_tag_qa_state', 'allow_publish');
      $this->dropColumn('waffle_unit_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_unit_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_unit_qa_state', 'allow_review');
      $this->dropColumn('waffle_unit_qa_state', 'allow_publish');
    }
}
