<?php
class m140314_193016_qa_attributes extends CDbMigration
{
    public function up()
    {
        $this->addColumn('data_article_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('data_article_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'title_approved', 'BOOLEAN NULL');
        $this->addColumn('data_source_qa_state', 'title_proofed', 'BOOLEAN NULL');
        $this->addColumn('i18n_catalog_qa_state', 'po_contents_approved', 'BOOLEAN NULL');
        $this->addColumn('i18n_catalog_qa_state', 'po_contents_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_mp4_media_id_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_webm_media_id_approved', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_mp4_media_id_proofed', 'BOOLEAN NULL');
        $this->addColumn('video_file_qa_state', 'clip_webm_media_id_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'title_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'slug_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'json_import_media_id_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'po_contents_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'title_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'slug_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'json_import_media_id_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_qa_state', 'po_contents_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_thing_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_thing_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_thing_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_category_thing_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_data_source_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_indicator_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
        $this->createTable('waffle_publisher_qa_state', array(
                    'id' => 'BIGINT NOT NULL AUTO_INCREMENT',
                    'PRIMARY KEY (`id`)',
                ));
        $this->addColumn('waffle_publisher', 'waffle_publisher_qa_state_id', 'BIGINT NULL');
        $this->addForeignKey('waffle_publisher_qa_state_id_fk', 'waffle_publisher', 'waffle_publisher_qa_state_id', 'waffle_publisher_qa_state', 'id', 'SET NULL', 'SET NULL');
        $this->addColumn('waffle_publisher_qa_state', 'status', 'VARCHAR(255) NULL');
        $this->addColumn('waffle_publisher_qa_state', 'draft_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'reviewable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'publishable_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_en_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ar_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_bg_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ca_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_cs_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_da_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_de_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_en_gb_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_en_us_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_el_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_es_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_fi_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_fil_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_fr_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_hi_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_hr_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_hu_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_id_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_iw_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_it_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ja_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ko_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_lt_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_lv_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_nl_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_no_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_pl_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_pt_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_pt_br_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_pt_pt_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ro_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_ru_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_sk_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_sl_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_sr_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_sv_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_th_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_tr_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_uk_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_vi_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_zh_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_zh_cn_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'translate_into_zh_tw_validation_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'approval_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'proofing_progress', 'INT NULL');
        $this->addColumn('waffle_publisher_qa_state', 'allow_review', 'BOOLEAN NULL');
        $this->addColumn('waffle_publisher_qa_state', 'allow_publish', 'BOOLEAN NULL');
        $this->addColumn('waffle_publisher_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_publisher_qa_state', 'ref_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_publisher_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_publisher_qa_state', 'ref_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_tag_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'short_name_en_approved', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'name_en_proofed', 'BOOLEAN NULL');
        $this->addColumn('waffle_unit_qa_state', 'short_name_en_proofed', 'BOOLEAN NULL');
    }

    public function down()
    {
      $this->dropColumn('data_article_qa_state', 'title_approved');
      $this->dropColumn('data_article_qa_state', 'title_proofed');
      $this->dropColumn('data_source_qa_state', 'title_approved');
      $this->dropColumn('data_source_qa_state', 'title_proofed');
      $this->dropColumn('i18n_catalog_qa_state', 'po_contents_approved');
      $this->dropColumn('i18n_catalog_qa_state', 'po_contents_proofed');
      $this->dropColumn('video_file_qa_state', 'clip_mp4_media_id_approved');
      $this->dropColumn('video_file_qa_state', 'clip_webm_media_id_approved');
      $this->dropColumn('video_file_qa_state', 'clip_mp4_media_id_proofed');
      $this->dropColumn('video_file_qa_state', 'clip_webm_media_id_proofed');
      $this->dropColumn('waffle_qa_state', 'title_en_approved');
      $this->dropColumn('waffle_qa_state', 'slug_en_approved');
      $this->dropColumn('waffle_qa_state', 'json_import_media_id_approved');
      $this->dropColumn('waffle_qa_state', 'po_contents_approved');
      $this->dropColumn('waffle_qa_state', 'title_en_proofed');
      $this->dropColumn('waffle_qa_state', 'slug_en_proofed');
      $this->dropColumn('waffle_qa_state', 'json_import_media_id_proofed');
      $this->dropColumn('waffle_qa_state', 'po_contents_proofed');
      $this->dropColumn('waffle_category_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_category_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_category_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_category_qa_state', 'short_name_en_proofed');
      $this->dropColumn('waffle_category_thing_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_category_thing_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_category_thing_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_category_thing_qa_state', 'short_name_en_proofed');
      $this->dropColumn('waffle_data_source_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_data_source_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_data_source_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_data_source_qa_state', 'short_name_en_proofed');
      $this->dropColumn('waffle_indicator_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_indicator_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_indicator_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_indicator_qa_state', 'short_name_en_proofed');
      $this->dropForeignKey('waffle_publisher_qa_state_id_fk', 'waffle_publisher');
      $this->dropColumn('waffle_publisher', 'waffle_publisher_qa_state_id');
      $this->dropTable('waffle_publisher_qa_state');
      $this->dropColumn('waffle_publisher_qa_state', 'status');
      $this->dropColumn('waffle_publisher_qa_state', 'draft_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'reviewable_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'publishable_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_en_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ar_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_bg_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ca_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_cs_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_da_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_de_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_en_gb_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_en_us_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_el_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_es_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_fi_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_fil_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_fr_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_hi_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_hr_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_hu_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_id_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_iw_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_it_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ja_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ko_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_lt_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_lv_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_nl_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_no_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_pl_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_pt_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_pt_br_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_pt_pt_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ro_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_ru_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_sk_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_sl_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_sr_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_sv_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_th_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_tr_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_uk_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_vi_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_zh_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_zh_cn_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'translate_into_zh_tw_validation_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'approval_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'proofing_progress');
      $this->dropColumn('waffle_publisher_qa_state', 'allow_review');
      $this->dropColumn('waffle_publisher_qa_state', 'allow_publish');
      $this->dropColumn('waffle_publisher_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_publisher_qa_state', 'ref_approved');
      $this->dropColumn('waffle_publisher_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_publisher_qa_state', 'ref_proofed');
      $this->dropColumn('waffle_tag_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_tag_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_tag_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_tag_qa_state', 'short_name_en_proofed');
      $this->dropColumn('waffle_unit_qa_state', 'name_en_approved');
      $this->dropColumn('waffle_unit_qa_state', 'short_name_en_approved');
      $this->dropColumn('waffle_unit_qa_state', 'name_en_proofed');
      $this->dropColumn('waffle_unit_qa_state', 'short_name_en_proofed');
    }
}
