<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => '',
  'Chapter' => '',
  'Chapters' => '',
  'Create' => '',
  'Create {model}' => '',
  'Created' => '',
  'Data' => '',
  'Data Chunk' => '',
  'Data Chunks' => '',
  'Data Source' => '',
  'Data Sources' => '',
  'Delete' => '',
  'Do you want to delete this item?' => '',
  'Download Link' => '',
  'Download Links' => '',
  'Editable Detail View' => '',
  'Exercise' => '',
  'Exercises' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'File' => '',
  'Html Chunk' => '',
  'Html Chunks' => '',
  'ID' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Manage' => '',
  'Markup' => '',
  'Menu Label' => '',
  'Modified' => '',
  'Ordinal' => '',
  'Original Media' => '',
  'P3 Media' => 'File (Upload)',
  'Presentation' => '',
  'Presentations' => '',
  'Processed Media' => '',
  'Relations' => '',
  'Save' => '',
  'Search' => '',
  'Section' => '',
  'Section Content' => '',
  'Section Contents' => '',
  'Sections' => '',
  'Slideshow File' => '',
  'Slideshow Files' => '',
  'Slug' => '',
  'Spreadsheet File' => '',
  'Spreadsheet Files' => '',
  'Teachers Guide' => '',
  'Teachers Guides' => '',
  'The requested page does not exist.' => '',
  'Title' => '',
  'Update' => '',
  'Update {model}' => '',
  'Video File' => '',
  'Video Files' => '',
  'View' => '',
  'Viz View' => '',
  'Viz Views' => '',
  'Word File' => '',
  'Word Files' => '',
);
