<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Append Child Page' => '',
  'Append Sibling Page' => '',
  'Application' => '',
  'Body' => '',
  'Browse' => '',
  'Chapter contains no sections' => '',
  'Choose Language' => '',
  'Click Start upload' => '',
  'Create' => '',
  'DataChunks' => '',
  'Drag & drop the file you wish to upload or use the select button below' => '',
  'Email' => '',
  'Exercises' => '',
  'Index' => '',
  'List' => '',
  'Login' => '',
  'Logout' => '',
  'Manage' => '',
  'Media' => '',
  'Name' => '',
  'No processed media file available' => '',
  'Overview' => '',
  'Pages' => '',
  'Presentations' => '',
  'Profile' => '',
  'Rights' => '',
  'Section contains no sectionContents' => '',
  'Section content has no linked content' => '',
  'SectionContents' => '',
  'Settings' => '',
  'Sitemap' => '',
  'SpreadsheetFiles' => '',
  'Subject' => '',
  'Template' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => '',
  'Translation' => '',
  'Update' => '',
  'Upload' => '',
  'User' => '',
  'Users' => '',
  'Verification Code' => '',
  'When upload has been completed, click Save to return to the previous form' => '',
  'Widgets' => '',
);
